services:
  frontend:
    build:
      context: ./frontend/askala
    command: npm run dev -- --host
    working_dir: /app
    volumes:
      - ./frontend/askala:/app
      - /app/node_modules  # Prevents node_modules from being overwritten
    ports:
      - "5173:5173"
    depends_on:
      - backend
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/app:/backend/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_val:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  postgres_val:
